function imout = myimfcn(im)
%Image Processing Function
%
% IM    - input image.
% IMOUT - output image.
%

%--------------------------------------------------------------------------
% Auto-generated by imageBatchProcessor App. 
%
% When used by the App, this function will be called for every input image
% file automatically. IM contains the input image as a matrix. The output
% image contained in IMOUT will be automatically written as an image into
% the output folder.
%
% Replace the code line below with your code to create IMOUT from IM:
%--------------------------------------------------------------------------
 %im=getimage(handles.axes4);
  %      axes(handles.axes5);
%mycolourimg = imread('im');
%mycolourimg = imresize(mycolourimg,[1920,1080]);
%subplot(3, 2, 1);
%imshow(mycolourimg); 
%title('Original Colour Image');
   
      
      diff_im = imsubtract(im(:,:,1), rgb2gray(im)); 
      diff_im = medfilt2(diff_im, [3 3]);             
      diff_im = im2bw(diff_im,0.18);                   
      stats = regionprops(diff_im, 'BoundingBox', 'Centroid'); 
      
  
      % Remove all those pixels less than 300px
      diff_im = bwareaopen(diff_im,300);
    
    % Label all the connected components in the image.
     bw = bwlabel(diff_im, 8);
    
    % Here we do the image blob analysis.
    % We get a set of properties for each labeled region.
    stats = regionprops(bw, 'BoundingBox', 'Centroid');
    
    % Display the image
    %(mycolourimg)
  % axes(handles.axes5);
   %imshow(im);
    
    
  
    
    
    
    %This is a loop to bound the red objects in a rectangular box.
    for object = 1:length(stats)
        bb = stats(object).BoundingBox;
        bc = stats(object).Centroid;
        rectangle('Position',bb,'EdgeColor','g','LineWidth',2)
        plot(bc(1),bc(2), '-m+')
        a=text(bc(1)+15,bc(2), strcat('X: ', num2str(round(bc(1))), '    Y: ', num2str(round(bc(2))), '    Color: Red'));
        set(a, 'FontName', 'Arial', 'FontWeight', 'bold', 'FontSize', 12, 'Color', 'red');
hold on      
        imout = im;      
        
    end  
 
    
    
    


